=== m-marini/railways/Railways/src/main/resources/stations/station-1.2.5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: station-1.2.5.xsd,v 1.2 2012/02/08 22:03:34 marco Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.mmarini.org/railways-1.2.5"
	xmlns="http://www.mmarini.org/railways-1.2.5"
	elementFormDefault="qualified">	<xs:simpleType name="angleType">
		<xs:restriction base="xs:positiveInteger">
			<xs:maxInclusive value="360" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="versusType">
		<xs:restriction base="xs:string">
			<xs:pattern value="left|right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nonNegativeDecimal">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="nodeRefType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="index" use="required"
					type="xs:nonNegativeInteger" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="segmentType">
		<xs:sequence minOccurs="2" maxOccurs="2">
			<xs:element name="node" type="nodeRefType" />
		</xs:sequence>
		<xs:attribute name="length" type="nonNegativeDecimal"
			use="required" />
	</xs:complexType>
	<xs:complexType name="platformType">
		<xs:sequence minOccurs="2" maxOccurs="2">
			<xs:element name="node" type="nodeRefType" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="length" type="nonNegativeDecimal"
			use="required" />
	</xs:complexType>
	<xs:complexType name="curveType">
		<xs:sequence minOccurs="2" maxOccurs="2">
			<xs:element name="node" type="nodeRefType" />
		</xs:sequence>
		<xs:attribute name="length" type="nonNegativeDecimal"
			use="required" />
		<xs:attribute name="versus" type="versusType" use="required" />
		<xs:attribute name="gap" type="xs:integer" default="0" />
	</xs:complexType>
	<xs:complexType name="linkType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="platform" type="platformType" />
			<xs:element name="segment" type="segmentType" />
			<xs:element name="curve" type="curveType" />
		</xs:choice>
	</xs:complexType>	<xs:complexType name="deviatorNodeType">
		<xs:complexContent>
			<xs:extension base="baseNodeType">
				<xs:attribute name="deviated" type="xs:boolean"
					default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="lineNodeType">		<xs:attribute name="reference" type="xs:string" use="required" />
		<xs:attribute name="destination" type="xs:boolean"
			default="false" />
	</xs:complexType>
	<xs:complexType name="baseNodeType">
		<xs:simpleContent>
			<xs:extension base="xs:string" />
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="crossDeviatorNodeType">
		<xs:complexContent>
			<xs:extension base="baseNodeType">
				<xs:attribute name="angle" type="nonNegativeDecimal" />
				<xs:attribute name="deviated" type="xs:boolean"
					default="false" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="crossNodeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="angle" type="nonNegativeDecimal" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="nodeType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="line" type="lineNodeType" />
			<xs:element name="semaphore" type="baseNodeType" />
			<xs:element name="deviator" type="deviatorNodeType" />
			<xs:element name="point" type="baseNodeType" />
			<xs:element name="cross" type="crossNodeType" />
			<xs:element name="crossDeviator" type="crossDeviatorNodeType" />
			<xs:element name="deadtrack" type="baseNodeType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="stationType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="nodes" type="nodeType" />
			<xs:element name="links" type="linkType" />
		</xs:sequence>
		<xs:attribute name="reference" type="xs:string" use="required" />
		<xs:attribute name="direction" type="angleType" use="required" />
	</xs:complexType>
	<xs:element name="station" type="stationType" />
</xs:schema>

=== m-marini/railways/src/main/resources/stations/downville.station.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: downville.station.xml,v 1.2 2012/02/08 22:03:34 marco Exp $ -->
<station xmlns="http://www.mmarini.org/railways-1.2.5"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mmarini.org/railways-1.2.5 station-1.2.5.xsd"
	direction="135" reference="From Norton">
	<name>Downville Station</name>
	<nodes>
		<line reference="From Norton"/>
		<line reference="To Norton" destination="true"/>
		<line reference="From Newesl"/>
		<line reference="To Newesl" destination="true"/>
		<line reference="From Sowerth"/>
		<line reference="To Sowerth" destination="true"/>
		<line reference="From Southend"/>
		<line reference="To Southend" destination="true"/>

		<semaphore>Platform 1 SW</semaphore>
		<semaphore>Platform 2 SW</semaphore>
		<semaphore>Platform 3 SW</semaphore>
		<semaphore>Platform 4 SW</semaphore>
		<semaphore>Platform 5 SW</semaphore>
		<semaphore>Platform 6 SW</semaphore>
		<semaphore>Platform 7 SW</semaphore>
		<semaphore>Platform 8 SW</semaphore>

		<semaphore>Platform 1 SE</semaphore>
		<semaphore>Platform 2 SE</semaphore>
		<semaphore>Platform 3 SE</semaphore>
		<semaphore>Platform 4 SE</semaphore>
		<semaphore>Platform 5 SE</semaphore>
		<semaphore>Platform 6 SE</semaphore>
		<semaphore>Platform 7 SE</semaphore>
		<semaphore>Platform 8 SE</semaphore>

		<semaphore>From Norton S1</semaphore>
		<semaphore>To Norton S1</semaphore>
		<semaphore>To Newesl S1</semaphore>
		<semaphore>From Newesl S1</semaphore>
		<semaphore>From Sowerth S1</semaphore>
		<semaphore>To Sowerth S1</semaphore>
		<semaphore>To Southend S1</semaphore>
		<semaphore>From Southend S1</semaphore>

		<point>pt.2</point>
		<point>pt.3</point>
		<point>pt.4</point>
		<point>pt.5</point>
		<point>pt.6</point>
		<point>pt.7</point>
		<point>pt.8</point>
		<point>pt.9</point>
		<point>pt.10</point>
		<point>pt.11</point>
		<point>pt.12</point>
		<point>pt.13</point>

		<point>From Norton P1</point>
		<point>From Norton P2</point>
		<point>To Norton P1</point>
		<point>To Newesl P1</point>
		<point>To Newesl P2</point>
		<point>From Newesl P1</point>
		<point>From Newesl P2</point>
		<point>From Sowerth P1</point>
		<point>To Sowerth P1</point>
		<point>To Sowerth P2</point>
		<point>To Southend P1</point>
		<point>From Southend P1</point>
		<point>From Southend P2</point>

		<point>Platform 1 P1</point>
		<point>Platform 1 P2</point>
		<point>Platform 2 P1</point>
		<point>Platform 2 P2</point>
		<point>Platform 3 P1</point>
		<point>Platform 3 P2</point>
		<point>Platform 6 P1</point>
		<point>Platform 7 P1</point>
		<point>Platform 7 P2</point>
		<point>Platform 8 P1</point>
		<point>Platform 8 P2</point>

		<deviator>To Norton D1</deviator>
		<deviator>To Norton D2</deviator>
		<deviator>To Norton D3</deviator>
		<deviator>To Norton D4</deviator>
		<deviator>To Norton D5</deviator>

		<deviator>From Norton D1</deviator>
		<deviator deviated="true">From Norton D3</deviator>
		<deviator deviated="true">From Norton D2</deviator>

		<deviator>To Newesl D1</deviator>
		<deviator deviated="true">To Newesl D2</deviator>
		<deviator deviated="true">To Newesl D3</deviator>

		<deviator>From Newesl D1</deviator>
		<deviator>From Newesl D2</deviator>
		<deviator>From Newesl D3</deviator>
		<deviator>From Newesl D4</deviator>
		<deviator>From Newesl D5</deviator>

		<deviator>From Sowerth D1</deviator>
		<deviator>From Sowerth D2</deviator>
		<deviator>From Sowerth D3</deviator>
		<deviator>From Sowerth D4</deviator>
		<deviator>From Sowerth D5</deviator>

		<deviator>To Sowerth D1</deviator>
		<deviator deviated="true">To Sowerth D2</deviator>
		<deviator deviated="true">To Sowerth D3</deviator>

		<deviator>To Southend D1</deviator>
		<deviator>To Southend D2</deviator>
		<deviator>To Southend D3</deviator>
		<deviator>To Southend D4</deviator>
		<deviator>To Southend D5</deviator>

		<deviator>From Southend D1</deviator>
		<deviator deviated="true">From Southend D2</deviator>
		<deviator deviated="true">From Southend D3</deviator>

		<cross>West Cross</cross>
		<cross>East Cross</cross>
	</nodes>
	<links>
		<!-- From Norton line -->
		<segment length="8">
			<node index="0">From Norton</node>
			<node index="0">From Norton P1</node>
		</segment>
		<curve length="3" versus="left">
			<node index="1">From Norton P1</node>
			<node index="0">From Norton S1</node>
		</curve>
		<segment length="0.25">
			<node index="1">From Norton S1</node>
			<node index="0">From Norton D1</node>
		</segment>
		<segment length="2.5">
			<node index="1">From Norton D1</node>
			<node index="0">From Norton P2</node>
		</segment>
		<curve versus="left" length="1">
			<node index="1">From Norton P2</node>
			<node index="2">From Norton D2</node>
		</curve>
		<segment length="0">
			<node index="0">From Norton D2</node>
			<node index="0">From Norton D3</node>
		</segment>
		<segment length="0.5176380902050415246977976752481">
			<node index="1">From Norton D3</node>
			<node index="0">Platform 8 P1</node>
		</segment>
		<curve versus="right" length="1">
			<node index="1">Platform 8 P1</node>
			<node index="0">Platform 8 SW</node>
		</curve>
		<curve versus="right" length="1">
			<node index="2">From Norton D3</node>
			<node index="0">Platform 7 P1</node>
		</curve>
		<segment length="0.5">
			<node index="1">Platform 7 P1</node>
			<node index="0">Platform 7 SW</node>
		</segment>

		<!-- From Norton line to To Norton line -->
		<curve versus="right" length="1">
			<node index="2">From Norton D1</node>
			<node index="0">pt.2</node>
		</curve>
		<curve versus="left" length="1">
			<node index="1">pt.2</node>
			<node index="2">To Norton D1</node>
		</curve>

		<!-- To Norton line to From Norton line -->
		<curve versus="left" length="1">
			<node index="2">To Norton D4</node>
			<node index="0">pt.10</node>
		</curve>
		<segment length="0.5176380902050415246977976752481">
			<node index="1">pt.10</node>
			<node index="1">From Norton D2</node>
		</segment>

		<!-- To Norton line -->
		<segment length="8">
			<node index="0">To Norton</node>
			<node index="0">To Norton P1</node>
		</segment>
		<curve length="3" versus="left" gap="1">
			<node index="1">To Norton P1</node>
			<node index="0">To Norton S1</node>
		</curve>
		<segment length="1.25">
			<node index="1">To Norton S1</node>
			<node index="1">To Norton D1</node>
		</segment>
		<segment length="0">
			<node index="0">To Norton D1</node>
			<node index="0">To Norton D2</node>
		</segment>
		<segment length="1">
			<node index="1">To Norton D2</node>
			<node index="1">To Norton D3</node>
		</segment>
		<segment length="0">
			<node index="0">To Norton D3</node>
			<node index="0">To Norton D4</node>
		</segment>
		<segment length="1">
			<node index="1">To Norton D4</node>
			<node index="0">To Norton D5</node>
		</segment>
		<segment length="1">
			<node index="1">To Norton D5</node>
			<node index="0">Platform 5 SW</node>
		</segment>
		<curve versus="left" length="1">
			<node index="2">To Norton D5</node>
			<node index="0">Platform 6 P1</node>
		</curve>
		<curve versus="right" length="1">
			<node index="1">Platform 6 P1</node>
			<node index="0">Platform 6 SW</node>
		</curve>

		<!-- From Sowerth line -->
		<segment length="8">
			<node index="0">From Sowerth</node>
			<node index="0">From Sowerth P1</node>
		</segment>
		<curve versus="right" length="3" gap="1">
			<node index="1">From Sowerth P1</node>
			<node index="0">From Sowerth S1</node>
		</curve>
		<segment length="1.25">
			<node index="1">From Sowerth S1</node>
			<node index="1">From Sowerth D1</node>
		</segment>
		<segment length="0">
			<node index="0">From Sowerth D1</node>
			<node index="0">From Sowerth D2</node>
		</segment>
		<segment length="1">
			<node index="1">From Sowerth D2</node>
			<node index="1">From Sowerth D3</node>
		</segment>
		<segment length="0">
			<node index="0">From Sowerth D3</node>
			<node index="0">From Sowerth D4</node>
		</segment>
		<segment length="1">
			<node index="1">From Sowerth D4</node>
			<node index="0">From Sowerth D5</node>
		</segment>
		<segment length="1">
			<node index="1">From Sowerth D5</node>
			<node index="0">Platform 4 SW</node>
		</segment>

		<!-- To Sowerth line -->
		<segment length="8">
			<node index="0">To Sowerth</node>
			<node index="0">To Sowerth P1</node>
		</segment>
		<curve versus="right" length="3">
			<node index="1">To Sowerth P1</node>
			<node index="0">To Sowerth S1</node>
		</curve>
		<segment length="0.25">
			<node index="1">To Sowerth S1</node>
			<node index="0">To Sowerth D1</node>
		</segment>
		<segment length="2.5">
			<node index="1">To Sowerth D1</node>
			<node index="0">pt.12</node>
		</segment>
		<curve versus="right" length="1">
			<node index="1">pt.12</node>
			<node index="2">To Sowerth D2</node>
		</curve>
		<segment length="0">
			<node index="0">To Sowerth D2</node>
			<node index="0">To Sowerth D3</node>
		</segment>
		<segment length="0.5176380902050415246977976752481">
			<node index="1">To Sowerth D3</node>
			<node index="0">Platform 1 P1</node>
		</segment>
		<curve versus="left" length="1">
			<node index="1">Platform 1 P1</node>
			<node index="0">Platform 1 SW</node>
		</curve>
		<curve versus="left" length="1">
			<node index="2">To Sowerth D3</node>
			<node index="0">Platform 2 P1</node>
		</curve>
		<segment length="0.5">
			<node index="1">Platform 2 P1</node>
			<node index="0">Platform 2 SW</node>
		</segment>

		<platform name="Platform 1" length="10">
			<node index="1">Platform 1 SW</node>
			<node index="1">Platform 1 SE</node>
		</platform>
		<platform name="Platform 2" length="10">
			<node index="1">Platform 2 SW</node>
			<node index="1">Platform 2 SE</node>
		</platform>
		<platform name="Platform 3" length="10">
			<node index="1">Platform 3 SW</node>
			<node index="1">Platform 3 SE</node>
		</platform>
		<platform name="Platform 4" length="10">
			<node index="1">Platform 4 SW</node>
			<node index="1">Platform 4 SE</node>
